name: CI

on:
  push:

permissions:
  contents: read

jobs:
  default:
    name: Default
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true

      - name: Install goyacc
        run: make install-goyacc

      - name: Install UI dependencies
        run: make ui-install

      - name: Run tests
        run: make test
